language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: [7.0, hhvm, nightly]

notifications:
  email: tomaz.ahlin2@gmail.com

before_script:
  # Update composer and install dependencies
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar self-update
  - php composer.phar install --dev --prefer-dist

script:
  - bin/phpunit src/
  - bin/phpspec run
