ahlin_mailer.simple:
    path:     /simple
    defaults: { _controller: ahlin_mailer.controller.test:simpleAction }
    methods: [GET]

ahlin_mailer.advanced:
    path:     /advanced
    defaults: { _controller: ahlin_mailer.controller.test:advancedAction }
    methods: [GET]

ahlin_mailer.deferred:
    path:     /deferred
    defaults: { _controller: ahlin_mailer.controller.test:deferredAction }
    methods: [GET]